---
#- name: Create user
#  hosts: debian-02
#  gather_facts: no
#  become: true
#  roles:
#    - { role: common }

#- name: Install package 'nginx'
#  hosts: debian-02
#  become: true
#  roles:
#    - { role: http-server }

- name: Runnign container 'zookepeer'
  hosts: db
  become: true
  roles:
    - { role: zookepeer }
