---
# vars file for common
#
username: john
default_user_password: p@ssw0rd

download_file: http://deb.debian.org/debian/pool/main/b/base-files/base-files_10.3+deb10u9.dsc
download_directory: /opt/data_archives
